### ISSUE TITLE
Cannot remove header

### ISSUE THREAD

**Issue by klinstifen** [mitchelltmarino/MMM-RemoteCompliments#9]
Is it possible to remove the header entirely?  I have tried several combinations including:

- populated header: string in config.js with empty cell in google config doc (creates a header of 'MMM-REMOTECOMPLIMENTS') 
- populated header: string in config.js with single space in google config doc (creates an empty header but still has header horizontal line)
- empty header: string in config.js with single space in google config doc (creates an empty header but still has header horizontal line)
- empty string in config.js empty cell in google config doc (creates a header of 'MMM-REMOTECOMPLIMENTS') 

I am using MM 2.10.1 if that helps.

**Comment by emrahaslan** [comment]
try tihs :

.module.MMM-RemoteCompliments .module-header {
 display: none;
}

**Comment by klinstifen** [comment]
Thanks! I also added ```border-bottom:none;```
